# Generated by Django 5.2.6 on 2025-10-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0002_participante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
    ]
