# Generated by Django 5.2.6 on 2025-10-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0003_corrida'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teste',
            new_name='Topic',
        ),
    ]
