# Generated by Django 5.2.6 on 2025-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0004_rename_teste_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='texto',
            field=models.TextField(default='Texto padrão'),
        ),
    ]
