# Generated by Django 5.2.6 on 2025-10-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0006_participante_corrida_participante_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
