# Generated by Django 5.2.6 on 2025-10-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0009_alter_participante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
    ]
