# Generated by Django 5.2.6 on 2025-10-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0012_alter_participante_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='categoria',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='tamanho_camisa',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
