# Generated by Django 5.2.7 on 2025-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0014_alter_participante_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('equipe', models.CharField(blank=True, max_length=100, null=True)),
                ('tempo', models.CharField(max_length=20)),
                ('velocidade', models.CharField(max_length=20)),
            ],
        ),
    ]
