# Generated by Django 5.2.7 on 2025-11-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0017_arquivoexcel_corredor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='tempo',
        ),
        migrations.AddField(
            model_name='corredor',
            name='tempo_formatado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='corredor',
            name='tempo_segundos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='Vel_media',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
