# Generated by Django 5.2.7 on 2025-11-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0020_remove_corredor_arquivo_alter_corredor_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='equipe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
