# Generated by Django 5.2.7 on 2025-11-12 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0021_alter_corredor_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='arquivo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='corredores', to='api_s.arquivoexcel'),
            preserve_default=False,
        ),
    ]
