# Generated by Django 5.2.7 on 2025-11-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0023_remove_corredor_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_s.arquivoexcel'),
        ),
    ]
