# Generated by Django 5.2.7 on 2025-11-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0030_alter_corrida_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivoexcel',
            options={'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.AlterModelOptions(
            name='corrida',
            options={'verbose_name': 'Inscrição Corrida', 'verbose_name_plural': 'Inscrições Corridas'},
        ),
    ]
