# Generated by Django 5.2.7 on 2026-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0031_alter_arquivoexcel_options_alter_corrida_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoexcel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
