# Generated by Django 5.2.7 on 2026-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0032_arquivoexcel_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoexcel',
            name='local',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
