# Generated by Django 5.2.7 on 2026-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0038_alter_corredor_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
