# Generated by Django 5.2.7 on 2026-04-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0044_alter_participante_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
