# Generated by Django 5.2.6 on 2025-10-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0005_topic_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='corrida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='api_s.corrida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='equipe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
