# Generated by Django 5.2.6 on 2025-10-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0007_participante_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=14, unique=True),
        ),
    ]
