# Generated by Django 5.2.6 on 2025-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0008_participante_sexo_alter_participante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=14),
        ),
    ]
