# Generated by Django 5.2.6 on 2025-10-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0011_alter_participante_cpf_alter_participante_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, null=True),
        ),
    ]
