# Generated by Django 5.2.6 on 2025-10-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0013_participante_categoria_participante_tamanho_camisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='categoria',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
