# Generated by Django 5.2.7 on 2025-11-04 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0015_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.FileField(upload_to='resultados/', verbose_name='Arquivo de Resultados')),
                ('ArquivoResultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api_s.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
