# Generated by Django 5.2.6 on 2025-11-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0016_produto_resultadoimagem_delete_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colocacao', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=20)),
                ('equipe', models.CharField(max_length=100)),
                ('tempo', models.FloatField()),
                ('Vel_media', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resultadoimagem',
            name='ArquivoResultado',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='ResultadoImagem',
        ),
    ]
