# Generated by Django 5.2.7 on 2025-11-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0018_remove_corredor_tempo_corredor_tempo_formatado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='arquivo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_s.arquivoexcel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corredor',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
