# Generated by Django 5.2.7 on 2025-11-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0019_corredor_arquivo_alter_corredor_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='arquivo',
        ),
        migrations.AlterField(
            model_name='corredor',
            name='numero',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
