# Generated by Django 5.2.7 on 2025-11-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0022_corredor_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='arquivo',
        ),
    ]
