# Generated by Django 5.2.7 on 2025-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0024_corredor_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='corredor',
            options={'verbose_name': 'Classificação', 'verbose_name_plural': 'Classificações'},
        ),
    ]
