# Generated by Django 5.2.7 on 2025-11-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0025_resultados_alter_corredor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='resultados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_s.resultados'),
        ),
    ]
