# Generated by Django 5.2.7 on 2025-11-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0026_corredor_resultados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='resultados',
        ),
    ]
