# Generated by Django 5.2.7 on 2025-11-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0027_remove_corredor_resultados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivoexcel',
            options={'verbose_name': 'Kaue', 'verbose_name_plural': 'Kaues'},
        ),
        migrations.AlterModelOptions(
            name='corrida',
            options={'verbose_name': 'Corrida', 'verbose_name_plural': 'Corridas'},
        ),
    ]
