# Generated by Django 5.2.7 on 2025-11-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0028_alter_arquivoexcel_options_alter_corrida_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoexcel',
            name='data_corrida',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='arquivoexcel',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
