# Generated by Django 5.2.7 on 2025-11-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0029_arquivoexcel_data_corrida_alter_arquivoexcel_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corrida',
            options={'verbose_name': 'Corrida', 'verbose_name_plural': 'TCHAU CORRIDAS'},
        ),
    ]
