# Generated by Django 5.2.7 on 2026-02-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0033_arquivoexcel_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='corridas/'),
        ),
    ]
