# Generated by Django 5.2.7 on 2026-02-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0036_alter_corredor_participante_alter_participante_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api_s.participante'),
        ),
    ]
