# Generated by Django 5.2.7 on 2026-02-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0039_corredor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api_s.participante'),
        ),
    ]
