# Generated by Django 5.2.7 on 2026-03-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0040_alter_corredor_participante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='cpf',
        ),
    ]
