# Generated by Django 5.2.7 on 2026-03-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0041_remove_corredor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G')], default='M', max_length=1, null=True),
        ),
    ]
