# Generated by Django 5.2.7 on 2026-04-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0043_limpar_cpfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
