# Generated by Django 5.2.7 on 2026-05-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0047_add_production_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corredor',
            options={'verbose_name': 'Classificacao', 'verbose_name_plural': 'Classificacoes'},
        ),
        migrations.AlterModelOptions(
            name='corrida',
            options={'verbose_name': 'InscriÃ§Ã£o Corrida', 'verbose_name_plural': 'InscriÃ§Ãµes Corridas'},
        ),
        migrations.RenameIndex(
            model_name='corredor',
            new_name='api_s_corre_arquivo_d6011e_idx',
            old_name='api_s_corre_arquivo_15e3e2_idx',
        ),
        migrations.RenameIndex(
            model_name='corredor',
            new_name='api_s_corre_arquivo_4fdcc7_idx',
            old_name='api_s_corre_arquivo_35722b_idx',
        ),
    ]
