# Generated by Django 5.2.7 on 2026-05-01 17:16

import django.db.models.deletion
from django.db import migrations, models


def migrar_corridas_para_inscricoes(apps, schema_editor):
    Participante = apps.get_model('api_s', 'Participante')
    Inscricao = apps.get_model('api_s', 'Inscricao')

    inscricoes = []
    for participante in Participante.objects.exclude(corrida_id__isnull=True).iterator():
        inscricoes.append(
            Inscricao(
                participante_id=participante.id,
                corrida_id=participante.corrida_id,
            )
        )

    if inscricoes:
        Inscricao.objects.bulk_create(inscricoes, ignore_conflicts=True, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0048_alter_corredor_options_alter_corrida_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='api_s.corrida')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='api_s.participante')),
            ],
            options={
                'verbose_name': 'Inscricao',
                'verbose_name_plural': 'Inscricoes',
                'indexes': [models.Index(fields=['corrida', 'criada_em'], name='api_s_inscr_corrida_ae2ea9_idx'), models.Index(fields=['participante', 'criada_em'], name='api_s_inscr_partici_45cf26_idx')],
                'constraints': [models.UniqueConstraint(fields=('participante', 'corrida'), name='unique_participante_corrida')],
            },
        ),
        migrations.RunPython(migrar_corridas_para_inscricoes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='participante',
            name='corrida',
        ),
    ]
