# Generated by Django 5.2.7 on 2026-05-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0050_fix_admin_labels_and_category_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='local_evento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Local do evento'),
        ),
    ]
